version: 2.1
jobs:
  build:
    docker:
      - image: node:14.15.0-alpine
    steps:
      - checkout
      - run: apk add git python pkgconf pixman-dev cairo-dev pango-dev make g++ libjpeg-turbo-dev
      - run: git clone --depth 1 --branch v1.7.12 https://github.com/vector-im/element-web
      - run: cd element-web && yarn install && yarn build
